name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: nikicat/setup-deno@node24
        with:
          deno-version: v2.x

      - run: make check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: make test-go

  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: nikicat/setup-deno@node24
        with:
          deno-version: v2.x

      - run: make playwright-install BROWSER=${{ matrix.browser }}

      - run: make test-e2e-browser BROWSER=${{ matrix.browser }}
